version: '3.1'
services:
  web:
    build: .
    ports:
      - 53000:3000
    environment:
      RAILS_ENV: mysql
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Ex4mpl3
  adminer:
    image: adminer
    ports:
      - 58080:8080